apiVersion: apps/v1
kind: Deployment
metadata:
 name: petclinic-deployment
 namespace: petclinic
spec:
 selector:
   matchLabels:
     app: petclinic
 replicas: 3 # tells deployment to run 3 pods matching the template
 template:
   metadata:
     labels:
       app: petclinic
   spec:
     containers:
     - name: petclinic
       image: varmalx/jenkins
       ports:
       - containerPort: 8080