kind: Service
metadata:
 name: petclinic--svc
 namespace: petclinic
spec:
 type: ClusterIP
 ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP
     name: http
 selector:
   app: petclinic